/**
 * Curated list of vehicles supported by SunnyPilot / OpenPilot.
 * Used for validation and autocomplete on the client.
 */

export interface VehicleEntry {
  make: string;
  displayName: string;
  models: string[];
}

export const VERIFIED_VEHICLES: VehicleEntry[] = [
  {
    make: "toyota",
    displayName: "Toyota",
    models: [
      "Camry",
      "Camry Hybrid",
      "Corolla",
      "Corolla Cross Hybrid",
      "RAV4",
      "RAV4 Hybrid",
      "RAV4 Prime",
      "Highlander",
      "Highlander Hybrid",
      "Sienna",
      "Sequoia",
      "Tacoma",
      "Tundra",
      "Tundra Hybrid",
      "Prius",
      "Prius Prime",
      "Prius V",
      "Venza",
      "Crown",
      "Crown Hybrid",
      "bZ4X",
      "C-HR",
      "Land Cruiser",
      "Avalon",
      "Avalon Hybrid",
      "Mirai",
    ],
  },
  {
    make: "lexus",
    displayName: "Lexus",
    models: [
      "ES 250",
      "ES 300h",
      "ES 350",
      "IS 300",
      "IS 350",
      "NX 250",
      "NX 350",
      "NX 350h",
      "NX 450h+",
      "RX 300",
      "RX 350",
      "RX 350h",
      "RX 450h",
      "RX 450h+",
      "RX 500h",
      "GX 460",
      "UX 200",
      "UX 250h",
      "LC 500",
      "LC 500h",
      "LS 500",
      "LS 500h",
      "RC 300",
    ],
  },
  {
    make: "honda",
    displayName: "Honda",
    models: [
      "Accord",
      "Accord Hybrid",
      "Civic",
      "Civic e:HEV",
      "CR-V",
      "CR-V Hybrid",
      "Pilot",
      "Passport",
      "Ridgeline",
      "Odyssey",
      "Insight",
      "Prologue",
      "HR-V",
      "Fit",
    ],
  },
  {
    make: "acura",
    displayName: "Acura",
    models: [
      "MDX",
      "MDX Sport Hybrid",
      "RDX",
      "RLX Sport Hybrid",
      "TLX",
      "ILX",
    ],
  },
  {
    make: "hyundai",
    displayName: "Hyundai",
    models: [
      "Sonata",
      "Sonata Hybrid",
      "Elantra",
      "Elantra Hybrid",
      "Tucson",
      "Tucson Hybrid",
      "Tucson PHEV",
      "Santa Fe",
      "Santa Fe Hybrid",
      "Santa Fe PHEV",
      "Palisade",
      "Ioniq",
      "Ioniq Hybrid",
      "Ioniq Electric",
      "Ioniq 5",
      "Ioniq 6",
      "Kona",
      "Kona Electric",
      "Nexo",
      "Veloster N",
    ],
  },
  {
    make: "kia",
    displayName: "Kia",
    models: [
      "K5",
      "K5 Hybrid",
      "Forte",
      "Niro",
      "Niro Hybrid",
      "Niro EV",
      "Niro PHEV",
      "Sportage",
      "Sportage Hybrid",
      "Sportage PHEV",
      "Sorento",
      "Sorento Hybrid",
      "Sorento PHEV",
      "Telluride",
      "EV6",
      "EV9",
      "Stinger",
      "Seltos",
    ],
  },
  {
    make: "genesis",
    displayName: "Genesis",
    models: [
      "G70",
      "G80",
      "G80 Electrified",
      "G90",
      "GV70",
      "GV70 Electrified",
      "GV80",
    ],
  },
  {
    make: "gm",
    displayName: "GM",
    models: [
      "Buick Enclave",
      "Buick Envision",
      "Buick LaCrosse",
      "Cadillac ATS",
      "Cadillac CT4",
      "Cadillac CT5",
      "Cadillac CT6",
      "Cadillac Escalade",
      "Cadillac XT4",
      "Cadillac XT5",
      "Cadillac XT6",
      "Chevy Bolt EUV",
      "Chevy Bolt EV",
      "Chevy Colorado",
      "Chevy Equinox",
      "Chevy Malibu",
      "Chevy Silverado 1500",
      "Chevy Silverado 2500",
      "Chevy Suburban",
      "Chevy Tahoe",
      "Chevy Tracker",
      "Chevy Traverse",
      "Chevy Trailblazer",
      "GMC Acadia",
      "GMC Canyon",
      "GMC Envoy",
      "GMC Sierra 1500",
      "GMC Sierra 2500",
      "GMC Terrain",
      "GMC Yukon",
    ],
  },
  {
    make: "ford",
    displayName: "Ford",
    models: [
      "Bronco Sport",
      "Edge",
      "Escape",
      "Escape Hybrid",
      "Explorer",
      "F-150",
      "F-150 Hybrid",
      "F-150 Lightning",
      "Maverick",
      "Mustang Mach-E",
      "Transit Connect",
    ],
  },
  {
    make: "lincoln",
    displayName: "Lincoln",
    models: ["Aviator", "Corsair", "Corsair PHEV", "MKZ", "Navigator"],
  },
  {
    make: "chrysler",
    displayName: "Chrysler",
    models: ["Pacifica", "Pacifica Hybrid"],
  },
  {
    make: "jeep",
    displayName: "Jeep",
    models: [
      "Cherokee",
      "Grand Cherokee",
      "Grand Cherokee L",
      "Grand Cherokee 4xe",
      "Grand Wagoneer",
      "Wagoneer",
    ],
  },
  {
    make: "ram",
    displayName: "Ram",
    models: ["Ram 1500", "Ram 1500 TRX", "Ram 2500", "Ram 3500"],
  },
  {
    make: "volkswagen",
    displayName: "Volkswagen",
    models: [
      "Golf",
      "Golf GTI",
      "Golf GTE",
      "Golf R",
      "Golf SportWagen",
      "Passat",
      "Tiguan",
      "Touareg",
      "Atlas",
      "Atlas Cross Sport",
      "ID.3",
      "ID.4",
      "ID.5",
      "CC",
      "T-Roc",
      "T-Cross",
      "Taigo",
    ],
  },
  {
    make: "audi",
    displayName: "Audi",
    models: [
      "A3",
      "A3 e-tron",
      "A4",
      "A4 Allroad",
      "A5",
      "A6",
      "A6 Allroad",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q4 e-tron",
      "Q5",
      "Q5 PHEV",
      "Q7",
      "Q8",
      "Q8 e-tron",
      "e-tron",
      "e-tron Sportback",
      "Allroad",
      "S3",
      "S4",
      "S5",
      "S6",
    ],
  },
  {
    make: "subaru",
    displayName: "Subaru",
    models: [
      "Ascent",
      "Forester",
      "Impreza",
      "Legacy",
      "Outback",
      "XV / Crosstrek",
      "BRZ",
      "Solterra",
    ],
  },
  {
    make: "mazda",
    displayName: "Mazda",
    models: [
      "Mazda2",
      "Mazda3",
      "Mazda6",
      "CX-3",
      "CX-5",
      "CX-8",
      "CX-9",
      "CX-30",
      "CX-50",
      "CX-60",
      "MX-5 Miata",
    ],
  },
  {
    make: "nissan",
    displayName: "Nissan",
    models: [
      "Altima",
      "Ariya",
      "Leaf",
      "Murano",
      "Pathfinder",
      "Rogue",
      "Rogue Sport",
      "X-Trail",
      "Sentra",
      "Versa",
    ],
  },
  {
    make: "infiniti",
    displayName: "Infiniti",
    models: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  },
  {
    make: "other",
    displayName: "Other",
    models: [],
  },
];

/** Set of all known make keys (for fast lookup). */
export const KNOWN_MAKES = new Set(VERIFIED_VEHICLES.map((v) => v.make));

/** Returns the models list for a given make, or an empty array if unknown. */
export function getModelsForMake(make: string): string[] {
  return VERIFIED_VEHICLES.find((v) => v.make === make)?.models ?? [];
}
